# Generated by Django 6.0.7 on 2026-07-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_module', '0002_journalentry_journalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10),
        ),
    ]
