# Generated by Django 6.0.7 on 2026-07-24 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0005_attendance_is_late_attendance_late_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpjs_kesehatan_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('bpjs_ketenagakerjaan_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['min_income'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to='hr_module.employeeprofile'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_spv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spv_approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_SPV', 'Menunggu Persetujuan Supervisor'), ('PENDING_MANAGER', 'Menunggu Persetujuan Manager'), ('PENDING_HR', 'Menunggu Verifikasi HR'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING_SPV', max_length=20),
        ),
    ]
